/**
 * @file G_AccelHarmonic.hpp
 * 
 * @brief Computes the gradient of the Earth's harmonic gravity field.
 *
 * Calculates the gradient matrix of the acceleration vector generated by 
 * the Earth's harmonic gravity field at a given satellite position, using 
 * a gravity model up to specified degree and order.
 */

#ifndef _G_ACCELHARMONIC_
#define _G_ACCELHARMONIC_

#include "matrix.hpp"
#include "AccelHarmonic.hpp"

/**
 * @brief Computes the gradient of the Earth's harmonic gravity field.
 *
 * @param r      Satellite position vector in the true-of-date system.
 * @param U      Transformation matrix to the Earth-fixed body system.
 * @param n_max  Maximum degree of the gravity model.
 * @param m_max  Maximum order of the gravity model.
 * 
 * @return Reference to a 3×3 gradient matrix (partial derivatives of acceleration 
 *         components with respect to position components).
 */
Matrix& G_AccelHarmonic( Matrix& r, Matrix& U, int n_max, int m_max );

#endif